### ISSUE TITLE
Selection of Multiple Separation Options

### ISSUE THREAD

**Issue by keleog** [jemimaabu/list-alphabetizer#1]
**Problem**: *I cannot select multiple separation options at once.*

**Solution**: *Include the possibility of selecting all separation options simultaneously*.

**Additional Context**: *Should be able to solve this.*

![issue](https://user-images.githubusercontent.com/11840053/51784918-9573b800-2150-11e9-951a-43f657a21084.jpg)

**Comment by cyborg-nomade** [comment]
hi there, you're looking to solve this through changing the radio-button to a checkbox-button, or you're looking for some other kind of solution? either way, i could work on this issue.
