### ISSUE TITLE
Copy To Clipboard not working

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/list-alphabetizer#2]
Text is not copied to clipboard after clicking 'Copy to clipboard' button.

Check copySortedList function in [index.js](https://github.com/jemimaabu/list-alphabetizer/blob/master/index.js#L96)

**Comment by schezfaz** [comment]
Hey jemimaabu! I would like to work on this issue of making the copy to clipboard function functional! May I go ahead with it?

**Comment by jemimaabu** [comment]
> Hey jemimaabu! I would like to work on this issue of making the copy to clipboard function functional! May I go ahead with it?

Sure thing

**Comment by jemimaabu** [comment]
Merged!
