### ISSUE TITLE
Copy Button always enabled

### ISSUE THREAD

**Issue by oguduvictor** [jemimaabu/list-alphabetizer#6]
**Problem**: *When i go to the site and click copy, it copies blank. I should not see the copy when there is nothing to copy*

**Comment by bhuvansingla** [comment]
I will like to fix this.

**Comment by avashNekros** [comment]
I have fixed this issue :)

**Comment by jemimaabu** [comment]
> I will like to fix this.

The issue has been fixed but you can look around other repositories for something to work on :)
